# My Top 10 Tensor Functions and Methods

# 1: Creating Tensors

In [1]:
import torch


m = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# 2: Checking the Shape

In [2]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [3]:
print(m.shape)

torch.Size([2, 3])


# 3: Checking the Rank / Number of Dimensions

In [4]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
print(m.ndim)

2


In [6]:
print(len(m.shape))

2


# 4: Checking the Data Type

In [7]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
print(m.dtype)

torch.float32


In [9]:
other_m = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
print(other_m)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
print(other_m.dtype)

torch.int64


# 5: Creating a Tensor From NumPy Arrays

In [11]:
import numpy as np

np_ary = np.array([1., 2., 3.])
m2 = torch.from_numpy(np_ary)

print(m2)

tensor([1., 2., 3.], dtype=torch.float64)


In [12]:
m3 = torch.tensor(np_ary)

print(m3)

tensor([1., 2., 3.], dtype=torch.float64)


# 6: Changing Data Types

In [13]:
print(m2.dtype)

torch.float64


In [14]:
m2 = m2.to(torch.float32)
print(m2.dtype)

torch.float32


# 7: Checking the Device Type

In [15]:
m2.device

device(type='cpu')

# 8: Changing the Tensor Shape

In [16]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [17]:
print(m.view(3, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [18]:
print(m.view(-1, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [19]:
print(m.view(3, -1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


# 9: Transposing a Tensor

In [20]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [21]:
print(m.T)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# 10: Multiplying Matrices

In [22]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [23]:
print(m.T)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [24]:
m.matmul(m.T)

tensor([[14., 32.],
        [32., 77.]])

In [25]:
a = torch.tensor([1., 2., 3.])
a.dot(a)

tensor(14.)

In [26]:
a = torch.tensor([1., 2., 3.])
a.matmul(a)

tensor(14.)