# My Top 10 Tensor Functions and Methods

# 1: Creating Tensors

In [41]:
import torch


m = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
print(v)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# 2: Checking the Shape

In [56]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [58]:
print(m.shape)

torch.Size([2, 3])


# 3: Checking the Rank / Number of Dimensions

In [61]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [59]:
print(m.ndim)

2


In [60]:
print(len(m.shape))

2


# 4: Checking the Data Type

In [63]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [62]:
print(m.dtype)

torch.float32


In [64]:
other_m = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
print(other_m)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [65]:
print(other_m.dtype)

torch.int64


# 5: Creating a Tensor From NumPy Arrays

In [66]:
import numpy as np

np_ary = np.array([1., 2., 3.])
m2 = torch.from_numpy(np_ary)

print(m2)

tensor([1., 2., 3.], dtype=torch.float64)


In [67]:
m3 = torch.tensor(np_ary)

print(m3)

tensor([1., 2., 3.], dtype=torch.float64)


# 6: Changing Data Types

In [68]:
print(m2.dtype)

torch.float64


In [47]:
m2 = m2.to(torch.float32)
print(m2.dtype)

torch.float32


# 7: Checking the Device Type

In [48]:
m2.device

device(type='cpu')

# 8: Changing the Tensor Shape

In [49]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [50]:
print(m.view(3, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [69]:
print(m.view(-1, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [70]:
print(m.view(3, -1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


# 9: Transposing a Tensor

In [51]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [52]:
print(m.T)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# 10: Multiplying Matrices

In [71]:
print(m)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [72]:
print(m.T)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [73]:
m.matmul(m.T)

tensor([[14., 32.],
        [32., 77.]])

In [75]:
a = torch.tensor([1., 2., 3.])
a.dot(a)

tensor(14.)

In [76]:
a = torch.tensor([1., 2., 3.])
a.matmul(a)

tensor(14.)